### PR TITLE
Review code

### PR DESCRIPTION
**Pull request by estebanmual**

### CODE REVIEW

**Comment by estebanmual** [comment]
- We need to make all the changes that are ask by the Linters.

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @Estebanmual , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Note:
I understand your point that the other files aren't showing up that's why you were not able to check them. I will suggest you go into the files directory, and take a look at the files. Later when making a review, inform your teammate about that specific file and what you think they should work on improving. 

## Required Changes ♻️
_Check the comments under the review._

You can also consider:
- [ ] Providing feedback on why it's necessary to make application linters error-free
      - Example: _"By the look of things you do have some linter errors. Linter help to 
      identifying errors when you use standard rules. It will be nice if you could fix them. "_
- [ ] I suggest making at least 2 comments after reviewing all the files.
Please use the guide on [how to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-communicate, in coming up with a review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by estebanmual** [comment]
### Required Changes ♻️

- [ ] By the look of things you do have some linter errors. Linter help to identify errors when you use standard rules. It will be nice if you could fix them. 
- [ ] There is a "meta" and "script " element outside "head". 
- [ ]  I would include a "header" tag to identify easier that section. Try to change the "div" tag to the "header" tag.  

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by Lordkaito — APPROVED** [review]
Hi @Estebanmual , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] [OPTIONAL] I suggest always making sure that linters are green before doing any review. This will help not only to know when a PR is able to be merged, but also to correct some common errors. Remember that linters are no more than commonly used rules to some kind of code or language, so following them is a good practice.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
